kind: Service
apiVersion: v1
metadata:
  # Service Name
  name: hello-world-flask
spec:
  selector:
    app: hello-world-flask
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer